### ISSUE TITLE
[Issue] Failed to Install-Package with `-RequiredVersion` option

### ISSUE THREAD

**Issue by dougpuob** [jianyunt/ChocolateyGet#20] opened 2021-01-21 02:56 UTC
Hi @jianyunt, thank you for your project. It makes script easier to install packages with choco. I found a tricky behavior, seems like an issue when I Install-Package with the `-RequiredVersion` option.
 
## ❌Failed case
`Install-Package -Provider ChocolateyGet -ErrorAction Stop -Verbose -AcceptLicense ninja -RequiredVersion 1.10.2`
VERBOSE: Using the provider 'ChocolateyGet' for searching packages.
VERBOSE: Source selected: chocolatey
Install-Package: No match was found for the specified search criteria and package name 'ninja'. Try Get-PackageSource to see all available registered package sources.

## ✅Passed case 
`Install-Package -Provider ChocolateyGet -ErrorAction Stop -Verbose -AcceptLicense ninja`
VERBOSE: Using the provider 'ChocolateyGet' for searching packages.
VERBOSE: Performing the operation "Install Package" on target "Package 'ninja' version '1.10.2' from 'chocolatey'.".

![image](https://user-images.githubusercontent.com/3453968/105273508-63c64800-5bd6-11eb-9aaa-afc89e81a248.png)

**Comment by ethanbergstrom** [comment] 2021-01-23 15:23
Hey @dougpuob,

Glad to hear ChocolateyGet is making life easier for you!

The issue you're describing seems to be more of a quirk with choco itself, rather than ChocolateyGet. 

If you run `Install-Package` or `Find-Package` with the `-debug` flag, it will actually list out the command line arguments passed to choco.exe. For ninja 1.10.2, that's `choco.exe search ninja --version 1.10.2 --source Chocolatey` which also returns no results. 

From what I can find, this seems to be related to [this choco issue](https://github.com/chocolatey/choco/issues/1004) that was opened a while ago, but is now closed and doesn't look like anyone is going to fix it. It looks like most folks are working around the problem by passing the `--exact` flag to choco, which skips package description text search and assumes your search text is the exact package name you want. 

Since ChocolateyGet is going to return whatever choco.exe does, what you'd probably need to run is:
`Install-Package ninja -ProviderName ChocolateyGet -RequiredVersion 1.10.2 -AdditionalArguments '--exact'`

Hope that works for you!

**Comment by ethanbergstrom** [comment] 2021-01-23 15:48
Actually, thinking about this a little more, I think I could make that experience better: to assume `--exact` behavior if package name and required version are specified.

**Comment by ethanbergstrom** [comment] 2021-01-23 17:20
Will need to downgrade the version of the choco Native API DLL to version 0.10.13 due to [a different choco issue](https://github.com/chocolatey/choco/issues/1843) that won't be fixed until the 0.10.16 API is released in order for the `exact` behavior to work with the OneGet `MinimumVersion`\ `MaximumVersion`\ `AllVersions` flags.

**Closed as completed** 2021-01-23 22:00 UTC
Labels: enhancement

**Comment by ethanbergstrom** [comment] 2021-01-23 22:29
@dougpuob,

ChocolateyGet v2.1.0 is now out on PSGallery, and my tests indicate it now works without having to sometimes pass `-AdditionalArguments '--exact'` depending on how many results match in the repository. 

This does however, introduce a possible new with issue with `-MaximumVersion` and `-AllVersion` flags that is in turn caused by a defect in Chocolatey itself, but there are a few workarounds available. 

Please see the updated documentation in [the readme](https://github.com/jianyunt/ChocolateyGet#cli-package-search-with-maximumversion--allversions-return-unexpected-results) for more details.
